"use client";

import { useState, useEffect, useRef } from "react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);

const TABS = [
  {
    id: "tryon",
    label: "Virtual Try-On",
    heading: "See yourself in any outfit — instantly",
    bullets: [
      "Upload a selfie once; use it forever",
      "Paste any Amazon or retailer URL to add a garment",
      "Photorealistic generation in under 10 seconds",
    ],
    color: "#8b6fe8",
    placeholder: "Try-On Preview",
  },
  {
    id: "scenes",
    label: "Event Scenes",
    heading: "Drop yourself into any world",
    bullets: [
      "Beach wedding, red carpet, Parisian café — any setting",
      "AI places you and your outfit naturally in the scene",
      "Perfect for imagining an outfit before a real event",
    ],
    color: "#5cb8b2",
    placeholder: "Scene Preview",
  },
  {
    id: "video",
    label: "Ramp Video",
    heading: "Animate your look in 5 seconds",
    bullets: [
      "Turn any try-on into a runway walk clip",
      "5-second video generated by Runway AI",
      "Download and share directly from the Studio",
    ],
    color: "#e87f8a",
    placeholder: "Video Preview",
  },
  {
    id: "stylist",
    label: "AI Stylist",
    heading: "A stylist that knows your closet",
    bullets: [
      "Chat with Aria — she knows every item you own",
      "Ask for outfit suggestions, styling tips, or packing lists",
      "Voice-enabled with a live avatar",
    ],
    color: "#6b8e5f",
    placeholder: "Stylist Preview",
  },
];

export default function FeaturesTab() {
  const [active, setActive] = useState(0);
  const sectionRef = useRef<HTMLElement>(null);
  const contentRef = useRef<HTMLDivElement>(null);
  const indicatorRef = useRef<HTMLDivElement>(null);
  const tabRefs = useRef<(HTMLButtonElement | null)[]>([]);

  // Slide indicator on tab change
  useEffect(() => {
    const tab = tabRefs.current[active];
    const indicator = indicatorRef.current;
    if (!tab || !indicator) return;
    gsap.to(indicator, {
      x: tab.offsetLeft,
      width: tab.offsetWidth,
      duration: 0.35,
      ease: "power2.inOut",
    });
  }, [active]);

  // Crossfade content on tab change
  const handleTabChange = (i: number) => {
    if (i === active) return;
    const el = contentRef.current;
    if (!el) { setActive(i); return; }
    gsap.killTweensOf(el);
    gsap.to(el, {
      opacity: 0,
      y: 12,
      duration: 0.2,
      onComplete: () => {
        setActive(i);
        gsap.fromTo(el, { opacity: 0, y: 12 }, { opacity: 1, y: 0, duration: 0.3, ease: "power2.out" });
      },
    });
  };

  // Section entrance with scrub
  useEffect(() => {
    const ctx = gsap.context(() => {
      gsap.fromTo(
        sectionRef.current,
        { opacity: 0, y: 60 },
        {
          opacity: 1,
          y: 0,
          scrollTrigger: {
            scroller: ".landing-scroll",
            trigger: sectionRef.current,
            start: "top 85%",
            end: "top 50%",
            scrub: 0.8,
          },
        }
      );
    });
    return () => ctx.revert();
  }, []);

  const tab = TABS[active];

  return (
    <section
      id="features"
      ref={sectionRef}
      style={{ padding: "120px 32px", background: "var(--surface)" }}
    >
      <div style={{ maxWidth: 1200, margin: "0 auto" }}>
        {/* Header */}
        <div style={{ marginBottom: 56, maxWidth: 560 }}>
          <p
            style={{
              fontSize: 12,
              letterSpacing: "0.12em",
              textTransform: "uppercase",
              color: "var(--text-muted)",
              margin: "0 0 16px",
              fontFamily: "JetBrains Mono, monospace",
            }}
          >
            Features
          </p>
          <h2
            className="font-display"
            style={{ fontSize: "clamp(32px, 4vw, 52px)", color: "var(--text)", margin: 0, fontWeight: 500 }}
          >
            Everything you need to dress smarter
          </h2>
        </div>

        {/* Tab bar */}
        <div style={{ position: "relative", marginBottom: 56, borderBottom: "1px solid var(--border)" }}>
          <div style={{ display: "flex", gap: 0 }}>
            {TABS.map((t, i) => (
              <button
                key={t.id}
                ref={(el) => { tabRefs.current[i] = el; }}
                onClick={() => handleTabChange(i)}
                style={{
                  background: "none",
                  border: "none",
                  padding: "14px 28px",
                  fontSize: 14,
                  color: active === i ? "var(--ink)" : "var(--text-muted)",
                  fontWeight: active === i ? 600 : 400,
                  cursor: "pointer",
                  letterSpacing: "0.02em",
                  transition: "color 0.2s",
                  fontFamily: "Public Sans, sans-serif",
                  whiteSpace: "nowrap",
                }}
              >
                {t.label}
              </button>
            ))}
          </div>
          {/* Sliding indicator */}
          <div
            ref={indicatorRef}
            style={{
              position: "absolute",
              bottom: -1,
              height: 2,
              background: "var(--ink)",
              width: 0,
              left: 0,
            }}
          />
        </div>

        {/* Content panel */}
        <div
          ref={contentRef}
          style={{
            display: "grid",
            gridTemplateColumns: "1fr 1fr",
            gap: 80,
            alignItems: "center",
          }}
        >
          {/* Text */}
          <div>
            <h3
              className="font-display"
              style={{ fontSize: "clamp(24px, 3vw, 38px)", color: "var(--text)", margin: "0 0 28px", fontWeight: 500 }}
            >
              {tab.heading}
            </h3>
            <ul style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: 16 }}>
              {tab.bullets.map((b, i) => (
                <li key={i} style={{ display: "flex", gap: 12, alignItems: "flex-start" }}>
                  <span
                    style={{
                      width: 6,
                      height: 6,
                      borderRadius: "50%",
                      background: tab.color,
                      flexShrink: 0,
                      marginTop: 8,
                    }}
                  />
                  <span style={{ fontSize: 16, color: "var(--text-muted)", lineHeight: 1.6 }}>{b}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Visual placeholder */}
          <div
            style={{
              aspectRatio: "4/3",
              background: `${tab.color}18`,
              border: `1px solid ${tab.color}40`,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
            }}
          >
            <span
              style={{
                fontFamily: "JetBrains Mono, monospace",
                fontSize: 13,
                color: tab.color,
                letterSpacing: "0.08em",
                textTransform: "uppercase",
              }}
            >
              {tab.placeholder}
            </span>
          </div>
        </div>
      </div>
    </section>
  );
}
